on:
  workflow_call:
    inputs:
      container-name:
        required: true
        type: string

jobs:
  test-container:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3
    
      - name: 'Build container'
        run: |
          docker-compose -f ${{ inputs.container-name }}/docker-compose.yml up -d
          
      - name: 'Wait until container is healthy'
        uses: raschmitt/wait-for-healthy-container/@v1
        with:
          container-name: ${{ inputs.container-name }}